### ISSUE TITLE
These scopes is useful.

### ISSUE THREAD

**Issue by youngjuning** [atom-community/autocomplete-paths#172]
```css
scopes: [
      {
        scopes: ['source.css.embedded.html'],
        prefixes: [
          'url\\([\'"]?'
        ],
        extensions: ['png', 'gif', 'jpeg', 'jpg'],
        relative: true
      },
      {
        scopes: ['source.css.less'],
        prefixes: [
          'import\\s+[\'"]',
        ],
        extensions: ['less'],
        relative: true
      }
    ]
```
